### ISSUE TITLE
[US13] - ver lend

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#107]
### Descrição:

Paulo vinícius deseja acessar uma solicitação de empréstimo para poder visualizá-la

### Tarefas:

- [x] Abrir a pagina de lend ao clicar no card. 
- [x] Mostrar os dados do lend

### Critérios de aceitação:

- Paulo vinícius deve conseguir ver todos os dados lend;
- CI estar passando ;
- Respeitar todas as orientações acima.

### Tela
![request-page](https://user-images.githubusercontent.com/34384624/111880816-5d610c00-898c-11eb-9b57-d8c033be28e2.jpg)

**Comment by matheusyanmonteiro** [comment]
Foi feito pareamento hoje com o @Matheusafonsouza e o @viniciussaturnino também estava presente ajudando-nos a fazer a issue com dicas e na pesquisa da documentação do flutter.
