### ISSUE TITLE
[US10] - Ver suas solicitações

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#120]
### Descrição:

Paulo vinícius deseja acessar seus registros de solicitação de empréstimos para poder acompanha-las

### Tarefas:

- [x] Criar serviço;
- [x] Llistar solicitações do paulo;

### Critérios de aceitação:

- Paulo vinícius deverá conseguir  ver suas solicitações;
- CI estar passando ;
- Respeitar todas as orientações acima.

### Tela
![home-page (1)](https://user-images.githubusercontent.com/34384624/112724216-08c01280-8ef1-11eb-86a4-88a7d675db0d.jpg)

**Comment by viniciussaturnino** [comment]
![image](https://user-images.githubusercontent.com/49040839/113081865-d8f26280-91af-11eb-95bd-c3670e6ed015.png)
Fizemos a página de pedidos solicitados e emprestados
