### ISSUE TITLE
[US21] - confirmar emprestimo

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#122]
### Descrição:

Paulo vinícius  deseja confirmar um emprestimo para não ser mais notificado

### Tarefas:

- [x] Criar serviço para confirmar uma solicitação;

### Critérios de aceitação:

- Paulo vinícius deverá conseguir confirmar uma solicitação;
- CI estar passando ;
- Respeitar todas as orientações acima.

**Comment by youssef-md** [comment]
A issue já esta feita e está na Gateway e Request
