### ISSUE TITLE
[US17] - mostrar dados para emprestar

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#123]
### Descrição:

Lend.it deseja mostrar os dados de quem solicitou o empréstimo para o usuário que está disposto a ajudar 

### Tarefas:

- [x] Mostrar dados para pessoa que quer emprestar;
- [x] Abrir WhatsApp da pessoa;

### Critérios de aceitação:

- Paulo vinícius deverá conseguir ver dados da pessoa que quer ajudar;
- Paulo vinícius deverá conseguir entrar em contato com o usuário com a mensagem: Olá NOME_DA_PESSOA meu nome é NOME_DA_DESSOA e eu posso te ajudar;
- Paulo vinícius deverá conseguir entrar em copntato pelo whats para ajudar ;
- CI estar passando ;
- Respeitar todas as orientações acima.

**Comment by youssef-md** [comment]
Aparentemente [esta lib](https://pub.dev/packages/flutter_open_whatsapp) é o que queremos
