### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#130]
## Descrição da Issue

Configurar o Firebase para ter as notificações do sistema.

## Tasks:
- [x] Configurar o firebase
- [x] Ter exemplo de uma notifricação.

## Critérios de Aceitação:
- [x] Firebase configurado
- [x] Permitir fazer uma notificação

**Comment by youssef-md** [comment]
Uma alternativa para quando formos automatizar o envio é conectá-lo a gateway com esse [Server Integration](https://firebase.flutter.dev/docs/messaging/server-integration/#send-messages-to-topics)

**Comment by youssef-md** [comment]
A notificação está sendo enviada manualmente(criando lá no Firebase). Para as próximas issues de notificação deve-se configurar essa lógica de envio de notificação na gateway [aparentemente tem um endpoint pra isso](https://youtu.be/P9yUV-rVvFM?t=1531)

![image](https://user-images.githubusercontent.com/29265857/116841203-d9b35580-abae-11eb-82e5-e8a1c63d3374.png)
