### ISSUE TITLE
[US25] - feedback numerico

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#134]
### Descrição:

Paulo vinícius deseja avaliar o usuário o qual emprestei meu pertence numericamente  para registrar minha experiência

### Tarefas:

- [x] criar interface para feedback;

### Critérios de aceitação:

- Paulo vinícius deverá conseguir enviar feedback ;
- CI estar passando ;
- Respeitar todas as orientações acima.

### Tela (caso não tenha, delete essa parte)

- A issue deve ser pontuada;
- A issue deve ser delegada a alguém;
- A issue deve ter labels;

**Comment by mateusmaiamaia** [comment]
Fizemos o componente de rating star e criamos a tela de avaliação 

![image](https://user-images.githubusercontent.com/49040839/114632963-10740b00-9c96-11eb-95ed-99145b3ba68a.png)
