### ISSUE TITLE
[US29] -  Fazer denuncia

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#136]
### Descrição:

Paulo vinícius deseja fazer uma denúncia sobre um usuário que não seguiu os termos para que ele seja punido

### Tarefas:

- [x] integrar serviço

### Critérios de aceitação:

- Paulo vinícius deverá conseguir denunciar um usuariuo;
- CI estar passando ;
- Respeitar todas as orientações acima.

**Comment by viniciussaturnino** [comment]
Versão final da página com todas as integrações com o back feitas

![image](https://user-images.githubusercontent.com/49040839/115073267-76e36e00-9ece-11eb-83f0-4fe3b16b6ba8.png)
