### ISSUE TITLE
[US15] Deletar ajuda 

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#138]
## Descrição da Issue

Lend.it deseja deletar uma solicitação de empréstimo que não foi atendida por outro usuário para | não manter registros 

## Tasks:
- [ ] Criar serviço no back

## Critérios de Aceitação:
- [ ] Lend.it deve conseguir deletar uma lend que acabou o tempo

**Comment by lucasdutraf** [comment]
@mateusmaiamaia @Thais-ra @thiagompc 

Lembrem-se do seguinte: A issue de vocês também contempla a refatoração desses 3 endpoints e seus respectivos testes.

https://github.com/Lend-it/Request/blob/devel/project/api/views.py#L56

https://github.com/Lend-it/Request/blob/devel/project/api/views.py#L93

https://github.com/Lend-it/Request/blob/devel/project/api/views.py#L116


Conferir no frontend as rotas utilizadas, mas a ideia é:
* A filtragem por `end_date` ser aplicada em todas elas
* A filtragem pelo requester diferente do passado para o endpoint
* A filtragem pelo lender passado pelo endpoint

**A abordagem a ser utilizada cabe a vocês! Existe uma redundância nessas rotas mas vou deixar livre para vocês utilizarem suas ferramentas e concluírem o que faz sentido e respeita as regras de responsabilidade de código! :smile_cat:**
