### ISSUE TITLE
Verificar fluxo do app

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#143]
## Descrição da Issue
Passar pelas telas da aplicação e verificar se há bugs;

## Tasks:
- [ ] Passar por todas as paginas das telas;
- [ ] Criar as issues de bugs;

**Comment by viniciussaturnino** [comment]
Encontramos alguns erros no fluxo do app:

1 - Criar conta precisa fazer o POST somente qnd o usuario permitir localização (latitude e longetude sendo chamados como null)

2 - Permitir localização dá erro

3 - Listagem na home não está funcionando

4 - Listagem na pagina de pedidos não está funcionando

5 - Criar pedido não faz a requisição

6 - Pagina de avisos não tem ainda

7 - Página de profile dá erro nos lends quando não estão finalizados
