### ISSUE TITLE
Análise de dados Nunito

### ISSUE THREAD

**Issue by lucasdutraf** [fga-eps-mds/2020.2-Lend.it#155]
## Descrição da Issue
Análise da dados baseado [nesse](https://github.com/Lend-it/Analytics) notebook da release "Nunito"
## Tasks:
- [x] Atualizar campos necessários com os jsons gerados pela equipe
- [x] Rodar o jupyter notebook
## Critérios de Aceitação:
- [x] Métricas coletadas

**Comment by Matheusafonsouza** [comment]
Segue em anexo o PDF do analytics no nunito.
[analytics_Nunito.pdf](https://github.com/fga-eps-mds/2020.2-Lend.it/files/6446050/analytics_Nunito.pdf)
