### ISSUE TITLE
Análise de dados Raleway

### ISSUE THREAD

**Issue by lucasdutraf** [fga-eps-mds/2020.2-Lend.it#156]
## Descrição da Issue
Análise da dados baseado [nesse](https://github.com/Lend-it/Analytics) notebook da release "Raleway"
## Tasks:
- [x] Atualizar campos necessários com os jsons gerados pela equipe
- [x] Rodar o jupyter notebook
## Critérios de Aceitação:
- [x] Métricas coletadas

**Comment by viniciussaturnino** [comment]
[analytics-raleway.pdf](https://github.com/fga-eps-mds/2020.2-Lend.it/files/6446103/analytics-raleway.pdf)
