### ISSUE TITLE
Análise de dados ZenDots

### ISSUE THREAD

**Issue by lucasdutraf** [fga-eps-mds/2020.2-Lend.it#157]
## Descrição da Issue
Análise da dados baseado [nesse](https://github.com/Lend-it/Analytics) notebook da release "ZenDots"
## Tasks:
- [x] Atualizar campos necessários com os jsons gerados pela equipe
- [x] Rodar o jupyter notebook
## Critérios de Aceitação:
- [x] Métricas coletadas

**Comment by mateusmaiamaia** [comment]
[analytics.pdf](https://github.com/fga-eps-mds/2020.2-Lend.it/files/6446112/analytics.pdf)
