### ISSUE TITLE
Análise de dados Rubik

### ISSUE THREAD

**Issue by lucasdutraf** [fga-eps-mds/2020.2-Lend.it#158]
## Descrição da Issue
Análise da dados baseado [nesse](https://github.com/Lend-it/Analytics) notebook da release "Rubik"
## Tasks:
- [ ] Atualizar campos necessários com os jsons gerados pela equipe
- [ ] Rodar o jupyter notebook
## Critérios de Aceitação:
- [ ] Métricas coletadas

**Comment by Thais-ra** [comment]
[analytics.pdf](https://github.com/fga-eps-mds/2020.2-Lend.it/files/6446043/analytics.pdf)
