### ISSUE TITLE
Análise de dados Quicksand

### ISSUE THREAD

**Issue by lucasdutraf** [fga-eps-mds/2020.2-Lend.it#159]
## Descrição da Issue
Análise da dados baseado [nesse](https://github.com/Lend-it/Analytics) notebook da release "Quicksand"
## Tasks:
- [ ] Atualizar campos necessários com os jsons gerados pela equipe
- [ ] Rodar o jupyter notebook
## Critérios de Aceitação:
- [ ] Métricas coletadas

**Comment by thiagompc** [comment]
[quicksand_analytics.pdf](https://github.com/fga-eps-mds/2020.2-Lend.it/files/6446114/quicksand_analytics.pdf)
