### ISSUE TITLE
Atualizar notebook de análise de dados

### ISSUE THREAD

**Issue by lucasdutraf** [fga-eps-mds/2020.2-Lend.it#167]
## Descrição da Issue
Atualizar o repositório de Analytics com o novo notebook sugerido pelo professor.

## Requisitos
- [x] [Calcular e analisar as medidas de THROUGHPUT  m7, m8 e m9](https://discord.com/channels/805970484100988928/805970484100988931/842517116548022282)
- [ ] [Ponderar e agregar as medidas m1, m2, m3, m7, m8, m9.](https://discord.com/channels/805970484100988928/805970484100988931/842520042520051733)
    - [x] Estatística descritiva (ex: média, moda, mediana, desvio padrão, variância, mínimo, máximo ). A visualização dessas medidas de tendência central deve ser em tabela
    - [x] Tabela apresentando os percentis (0%-99%)
    - [ ] Matriz de correlação das medidas
- [ ] [Gráfico de pontos da distribuição com a exibição da reta que expressa a qualidade total  em diferentes visões (processo e produto) em múltiplas releases. Ou seja: totalAC1 totalAC2. Utilizar regressão linear numérica.](https://discord.com/channels/805970484100988928/805970484100988931/842520347240169472)
    - [ ] Gráfico de histograma
    - [ ] Gráfico de box-plot
    - [ ] O dataframe consolidado, com medidas e indicadores calculados de cada microsserviço,  deve possuir a seguinte estrutura: m1    m2    m3    m7    m8    m9    asc1    ac1    asc2    ac2    totalAC1    totalAC2     repository    version    ncloc        coverage
    - [ ] O dataframe consolidado e estruturado deve ser exportado para um arquivo .CSV. O nome do arquivo deve seguir o seguinte padrão: <fga-eps-mds-2020-2-NOME_PROJETO-qualidade-total-DATA_ANALISE>  onde, data-analise deve ter o formato: DD-MM-YYYY

## Critérios de Aceitação:
-  Notebook Configurado com o padrão do projeto lendit

**Comment by rogerioo** [comment]
- [x] Adicionar um dataframe consolidando medidas descritivas (linha: serviço | coluna: estatística)
