### ISSUE TITLE
Documento de visão

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#17]
Startar documento de visão

Seguir o template da IBM
https://www.ibm.com/support/knowledgecenter/pt-br/SSYMRC_6.0.5/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html

Segue um exemplo de como deve ficar
https://fga-eps-mds.github.io/2018.2-Kalkuli/docs/docVisao

Deve ter bibliografia e edições do arquivo como ta no kalkuli

**Comment by Thais-ra** [comment]
Criei uma branch para a issue e comitei a estrutura inicial do documento.

**Comment by Matheusafonsouza** [comment]
Criação dos subtópicos de finalidade e visão geral em introdução.
Feito em conjunto com os integrantes @mateuscunhamaia @viniciussaturnino @matheusyanmonteiro

**Comment by viniciussaturnino** [comment]
Preenchi os subtópicos resumo dos envolvidos, resumo dos usuários e principais necessidades dos usuários ou dos envolvidos. Fiz em call com o @Matheusafonsouza @mateuscunhamaia e @matheusyanmonteiro

**Comment by mateusmaiamaia** [comment]
Criação dos subtópicos oportunidade de negócios e descrição do problema.
Feito em conjunto com os integrantes @Matheusafonsouza @viniciussaturnino @matheusyanmonteiro

**Comment by matheusyanmonteiro** [comment]
Criação dos tópicos perfis dos envolvidos e alternativas e concorrências.
Feito em conjunto com os integrantes @mateuscunhamaia  @viniciussaturnino  @Matheusafonsouza

**Comment by Thais-ra** [comment]
Revisão gramatical e estrutural de todo o documento.
Feito em conjunto com @thiagompc

**Comment by Thais-ra** [comment]
Modificação de finalidade, resumo dos usuarios, principais necessidades dos usuários ou dos envolvidos e alternativas e concorrências.

**Comment by thiagompc** [comment]
Modificação de oportunidade de negócios e descrição do problema.

**Comment by lucasdutraf** [comment]
@thiagompc @Thais-ra @Matheusafonsouza @matheusyanmonteiro @mateuscunhamaia 
Melhorias sugeridas:
* Organizar os nomes dos envolvidos nas tabelas em bullet points
* Mudar de "professora" para professor
* Mudar no histórico de versão a última linha para v1.0

**Comment by Thais-ra** [comment]
Já tá definido o raio máximo de distância que vai aparecer no feed?

**Comment by viniciussaturnino** [comment]
@Thais-ra Na história de usuário ta 10km, mas não sei se é o valor final

**Comment by thiagompc** [comment]
* Criação do subtópico 4.4 e do tópico 5
* Modificaçãp do tópico 2.1
* Adição dos bullet points nos tópicos 3.4.2 e 3.4.3
* Adição do tópico 1.2 e 4.1

Feito em conjunto com @Thais-ra

**Comment by Thais-ra** [comment]
A [primeira versão](https://github.com/fga-eps-mds/EPS-2020-2-G1/blob/17_documento_visao/_docs/docVisao.md) tá finalizada.
