### ISSUE TITLE
Pesquisa do tema

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#18]
## Descrição da Issue
Deve trazer um compilado de dados e fontes que validem a ideia

## Critérios de Aceitação:
- [x] Comentario na issue com dados que validem a ideia

**Comment by Thais-ra** [comment]
Encontrei um app com a mesma ideia: http://temacucar.com/

**Comment by viniciussaturnino** [comment]
Encontrei 2 blogs, um que fala sobre os problemas da superprodução e lista algumas possíveis soluções envolvendo softwares (alguns não tão otimizados) e o outro que reforça o ponto levantado pelo @lucasdutraf na nossa reunião relacionada ao reuso de materiais (nesse caso na construção civil).

Links:

1 - Superprodução: como evitar desperdícios na indústria - https://blog.ploomes.com/index.php/2019/06/05/superproducao/#:~:text=Outra%20consequ%C3%AAncia%20do%20processamento%20excessivo,a%20proje%C3%A7%C3%A3o%20de%20resultados%20futuros.

2 - Entenda a importância do reaproveitamento de materiais na construção civil - https://ecogranito.com.br/blog/reaproveitamento-de-materiais/

**Comment by Matheusafonsouza** [comment]
Matéria sobre 8 problemas de desperdício em indústrias, a qual fala sobre perda por superprodução: https://www.agpr5.com/identifique-e-elimine-os-8-desperdicios-mais-comuns-na-industria-2/

Quantidade de matéria entregue aos PEVs em 2020:  https://www.guarulhos.sp.gov.br/index.php/article/pevs-receberam-mais-de-54-mil-toneladas-de-residuos-em-2020

**Comment by rogerioo** [comment]
Acrescentar explicações no Doc de Visão #17
