### ISSUE TITLE
Criação do template de documento

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#21]
## Descrição da Issue
criar template de documento que vai ser colocado na wiki. Segue o [MODELO](https://github.com/pax-app/Wiki/blob/master/modelo.md) proposto

## Tasks:
- [x] criar template de documento

## Critérios de Aceitação:
- [x] estar na wiki

**Comment by youssef-md** [comment]
O modelo proposto já está na wiki, [commit](https://github.com/fga-eps-mds/EPS-2020-2-G1/commit/2ceee230847fb1695d4c78c65c56da17ff35c7a0)
