### ISSUE TITLE
Dojo Flask

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#39]
## Descrição da Issue
Dar Dojo de Flask para o time de MDS

## Tasks:
- [x] Criar Dojo 
- [x] Dar o Dojo
- [x] Tirar dúvidas dos MDSs

**Comment by lucasdutraf** [comment]
Dojo a ser ministrado: https://github.com/lucasdutraf/dojo-flask

**Comment by lucasdutraf** [comment]
Dojo de flask acontecerá na sprint 3 por falta de disponibilidade na sprint 2 e, também, pela realização do dojo de Flutter #30

**Comment by lucasdutraf** [comment]
Será realizado hoje (01/03).

**Comment by lucasdutraf** [comment]
Dojo realizado. Disponível em: https://youtu.be/lTNLd__tEKc
