### ISSUE TITLE
Dinâmica de quebra gelo

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#5]
Criação de uma dinâmica para os membros de MDS e EPS se conhecerem e alinharem expectativas.

**Comment by rogerioo** [comment]
Para poder aproximar mais o membros do time e para que pudessem se conhecer melhor, foi proposta uma dinâmica, na última reunião do dia 03/02/2021, que foi pedido para cada um pensar em 3 música, durante 10 minutos, e compartilhar com os membros. As músicas deviam estar dentro de 3 propostas:
- Uma música que define sua personalidade
- Uma música que gosta cantada por uma pessoa/banda que odeia
- Uma música para ser tocada no seu funeral
