### ISSUE TITLE
Teste de usabilidade

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#53]
## Descrição da Issue
Fazer teste de usabilidade da aplicação.

## Tasks:
- [x] Criar cenarios
- [x] Rodar testes

## Critérios de Aceitação:
- [x] Documentar na wiki

**Comment by youssef-md** [comment]
@EsioFreitas, não acha que a task "Atualizar prototipo de medio nivel com uma v2" seja desnecessária para essa sprint? já que temos o protótipo de alta fidelidade para a próxima sprint, ele seria feito levando em conta os resultados dos testes desta sprint.

**Comment by EsioFreitas** [comment]
@youssef-md , faz muito sentido. Alterando

**Comment by youssef-md** [comment]
Eu e @mateuscunhamaia acabamos de criar os testes dos fluxos mais estratégicos. Como o UsabilityHub não deixa criarmos um único teste grande(pois ultrapassaria 2min, coisa que só premiuns podem) criamos 5 testes separados:

- [Emprestar/Pedir produto](https://app.usabilityhub.com/do/bd76f02ed528/e92b)
- [Confiança do usuário](https://app.usabilityhub.com/do/a64012e15619/cdaa)
- [Editar Localização / Perfil](https://app.usabilityhub.com/do/f2f30ab3d1eb/d0a8)
- [Produto Emprestado](https://app.usabilityhub.com/do/728c642f333f/bdc5)
- [Avaliar usuário](https://app.usabilityhub.com/do/8afbcea36921/4298)

**Comment by EsioFreitas** [comment]
@matheusyanmonteiro , documentar seguindo esse modelo https://pax-app.github.io/Wiki/#/docs/DS/dinamica-e-seminario-3/TesteDeUsabilidadeWireframe
