### ISSUE TITLE
Identidade visual

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#54]
## Descrição da Issue
Levantar opções para votação de identidade visual.
**Cor:** Deverá ter uma cor primaria baseada na psicologia das cores. Deverá ter uma cor secundaria complementar a cor primaria no circulo cromatico. Cores neutras (branco e preto)
**Fonte:** Uma fonte que se comunique bem na plataforma mobile.
**Logo:** Uma logo que converse bem com a proposta do aplicativo.

## Tasks:
- [x] Criar paleta
- [x] Escolher fonte
- [x] Criar logo

## Critérios de Aceitação:
- [x] respeitar a proposta da aplicação
- [x] Documentar na wiki

**Comment by EsioFreitas** [comment]
Segue referencia da psicologia das cores

![image](https://user-images.githubusercontent.com/34384624/108725325-0854e600-7505-11eb-8f7c-a35c516cc4e9.png)

**Comment by EsioFreitas** [comment]
Referencia de cor complementar 

![image](https://user-images.githubusercontent.com/34384624/108725541-4225ec80-7505-11eb-8b67-3ed7eeb3a393.png)

**Comment by EsioFreitas** [comment]
Por se tratar de uma aplicação que quer gerar confiança entre vizinhos, a melhor opção é o laranja. 

![image](https://user-images.githubusercontent.com/34384624/108726193-e6a82e80-7505-11eb-888a-abc3b2dd45ba.png)

**Comment by mateusmaiamaia** [comment]
Como a aplicação é baseada fortemente na confiança entre os usuários, as cores que melhor se adequam para essa aplicação são: o laranja e o azul. Segue abaixo algumas sugestões.
![Paleta_1](https://user-images.githubusercontent.com/48732066/109035745-b4363700-76a7-11eb-9d39-49f3d954e0b9.jpeg)
![Paleta_2](https://user-images.githubusercontent.com/48732066/109035750-b5676400-76a7-11eb-9f0a-be416c451342.jpeg)
![Paleta_3](https://user-images.githubusercontent.com/48732066/109035753-b5fffa80-76a7-11eb-9e49-078abd3d07ac.jpeg)
![Paleta_4](https://user-images.githubusercontent.com/48732066/109035754-b5fffa80-76a7-11eb-99ff-2114f40f2475.jpeg)
![Paleta_5](https://user-images.githubusercontent.com/48732066/109035756-b6989100-76a7-11eb-9fa2-aa18edcc848f.jpeg)

**Comment by mateusmaiamaia** [comment]
Para essa aplicação fontes que sejam amigáveis são uma excelente opção, por isso temos algumas sugestões de fontes:
Roboto
https://fonts.google.com/specimen/Roboto?preview.text_type=custom#standard-styles
Poppins
https://fonts.google.com/specimen/Poppins?preview.text_type=custom#standard-styles
Open Sans
https://fonts.google.com/specimen/Open+Sans?preview.text_type=custom#standard-styles
Merriweather
https://fonts.google.com/specimen/Merriweather?preview.text_type=custom#standard-styles

**Comment by EsioFreitas** [comment]
Tambem gosto da ideia do uso dos tons pasteis 

![image](https://user-images.githubusercontent.com/34384624/109051070-e3a16f80-76b8-11eb-9f3a-1fe94515365d.png)

**Comment by youssef-md** [comment]
Eu também gosto de cores menos saturadas, fica mais fácil para fazer uma composição e mais fraca aos olhos. Elas também são uma tendência em UI: https://bootcamp.uxdesign.cc/muted-colors-for-2021-45b7179762fa

### Cores:

* Partindo desta paleta análoga:
![image](https://user-images.githubusercontent.com/29265857/109169322-71836600-775e-11eb-8271-809dfb43ce55.png)

* Depois selecionando o laranja e o um azul mais saturado e adicionando o preto e branco:
![image](https://user-images.githubusercontent.com/29265857/109170733-cf647d80-775f-11eb-83a6-db2716e831ac.png)

* Removendo um pouco do contraste das cores cheguei em:
![image](https://user-images.githubusercontent.com/29265857/109170622-b8259000-775f-11eb-8dd2-40a43d0bcf6c.png)

* Cheguei em outra paleta ao escurecer mais as cores:
![image](https://user-images.githubusercontent.com/29265857/109171123-35e99b80-7760-11eb-83f5-88754bf22d26.png)


### Fontes:

Gosto das fontes sugeridas pelo @mateuscunhamaia , são boas fontes para a leitura, sugiro:
* [Poppins](https://fonts.google.com/specimen/Poppins?preview.text_type=custom#standard-styles) para títulos;
* [Roboto](https://fonts.google.com/specimen/Roboto?preview.text_type=custom&query=Roboto) ou [Open Sans](https://fonts.google.com/specimen/Open+Sans?preview.text_type=custom#standard-styles) para textos.

**Comment by EsioFreitas** [comment]
@youssef-md , muito lindo a composição final (paletas com cores mais escuras).

**Comment by youssef-md** [comment]
Decidimos as fontes: Poppins e Open Sans

**Comment by EsioFreitas** [comment]
@Thais-ra , para documentar essa parte seguindo esse padrao https://fga-eps-mds.github.io/2018.2-Kalkuli/docs/idVisual

**Comment by Thais-ra** [comment]
Para documentar na wiki eu crio um documento de identidade visual?

**Comment by youssef-md** [comment]
@Thais-ra sim, eu prefiro um slide, nele você vai explicar:
- A paleta de cores escolhida(o porquê delas com base na psicologia das cores, e variações mais claras [exemplo](https://www.somossimples.com.br/wp-content/uploads/2020/01/foto-blog-MIV-3.png)). 
- As duas fontes escolhidas(diferenciação de título e texto, e pela facilidade de leitura).
- E a logo(mostrando como usá-la e como não usá-la).

**Comment by youssef-md** [comment]
Vou mandar as logos para fazermos a votação via corações por aqui :heart: 

![image](https://user-images.githubusercontent.com/29265857/109981978-35ad4b00-7ce0-11eb-849d-1bb7cb92e26c.png)

**Comment by youssef-md** [comment]
![image](https://user-images.githubusercontent.com/29265857/109982084-507fbf80-7ce0-11eb-9b3a-15fff96d75a8.png)

**Comment by youssef-md** [comment]
![image](https://user-images.githubusercontent.com/29265857/109982410-a48aa400-7ce0-11eb-9dff-d76c320e76b1.png)

**Comment by youssef-md** [comment]
![image](https://user-images.githubusercontent.com/29265857/109982706-eb789980-7ce0-11eb-8fc9-b29672fee404.png)

**Comment by youssef-md** [comment]
![image](https://user-images.githubusercontent.com/29265857/109983842-faac1700-7ce1-11eb-9478-223f93ab8edf.png)

**Comment by youssef-md** [comment]
![image](https://user-images.githubusercontent.com/29265857/109983972-1ca59980-7ce2-11eb-9275-a651fe1f9e11.png)

**Comment by youssef-md** [comment]
![image](https://user-images.githubusercontent.com/29265857/109984059-2e873c80-7ce2-11eb-906d-f2bce9a72698.png)

**Comment by Thais-ra** [comment]
> ![image](https://user-images.githubusercontent.com/29265857/109983972-1ca59980-7ce2-11eb-9275-a651fe1f9e11.png)

Vocês tentaram fazer uma dessa com o laranja no fundo?

**Comment by youssef-md** [comment]
@Thais-ra aqui

![image](https://user-images.githubusercontent.com/29265857/109985618-b91c6b80-7ce3-11eb-8dd9-aecfc8045db5.png)

**Comment by youssef-md** [comment]
@Thais-ra aqui

![image](https://user-images.githubusercontent.com/29265857/109985618-b91c6b80-7ce3-11eb-8dd9-aecfc8045db5.png)

**Comment by youssef-md** [comment]
@Thais-ra aqui

![image](https://user-images.githubusercontent.com/29265857/109985618-b91c6b80-7ce3-11eb-8dd9-aecfc8045db5.png)

**Comment by youssef-md** [comment]
Criei o slide para o doc de Manual de Identidade Visual, [aqui](https://docs.google.com/presentation/d/1TAPAFwuNAQyJIA_cmxViIjyWL4yyMdaiHPi4Km1c5iA/edit?usp=sharing)
