### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#55]
## Descrição da Issue
Criação de um backmark da aplicação. 

## Tasks:
- [x] Listar concorrentes
- [x] Comparações

## Critérios de Aceitação:
- [x] Documentar na wiki

**Comment by EsioFreitas** [comment]
Foi criado o documento base e colocado na wiki

https://docs.google.com/spreadsheets/d/1ZOezECaF2HzOaepvFQeIcEBdmp-_Q0992gIFDl38poA/edit#gid=0

**Comment by Matheusafonsouza** [comment]
Curva de valor feita e já atualizada no documento base
