### ISSUE TITLE
Escolha do Nome

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#56]
## Descrição da Issue
Definir um nome para a aplicação

## Tasks:
- [x] Comentar na issue os nomes

## Critérios de Aceitação:
- [x] Documentar na wiki

**Comment by rogerioo** [comment]
Vamos votar isso no sábado @EsioFreitas ?

Porque não marcou todos nessa issue?

**Comment by EsioFreitas** [comment]
Isso! Mas já pode comentando os nomes que acha relevante aqui.

Em ter., 23 de fev. de 2021 às 18:30, Rogério Junior <
notifications@github.com> escreveu:

**Comment by EsioFreitas** [comment]
Pensei no nome: compartilha

**Comment by youssef-md** [comment]
Nomes que pensei até agora: Vizinhação

**Comment by Thais-ra** [comment]
Mboja'o - Significa compartilhar, dividir em tupi guarani.

**Comment by Thais-ra** [comment]
Ecomuniti
Ecoparti
Econium
Junto

**Comment by viniciussaturnino** [comment]
Lend
Lend.it
iShare

**Comment by mateusmaiamaia** [comment]
Pensei no nome: Share.it

**Comment by Matheusafonsouza** [comment]
Emprestou
E-pegou

**Comment by Thais-ra** [comment]
TakeIT

**Comment by thiagompc** [comment]
Tem aí?

**Comment by rogerioo** [comment]
Lend.It foi o vencedor!
