### ISSUE TITLE
Curva de valor

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#57]
## Descrição da Issue
Criação do documento de curva de valor

## Tasks:
- [x] Comparação com concorrentes

## Critérios de Aceitação:
- [x] Documentar na wiki

**Comment by EsioFreitas** [comment]
Documento base ja foi criado e colocado na wiki 

https://docs.google.com/spreadsheets/d/1OTZRhUmCe7vgSq4lucWq1xUlEKQPNecR/edit#gid=901159347

**Comment by Matheusafonsouza** [comment]
Benchmark feito e já atualizado no documento base
