### ISSUE TITLE
Estruturar ambiente Node

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#59]
## Descrição da Issue
Estruturar ambiente Node

## Tasks:
- [x] Estruturar ambiente Node

## Critérios de Aceitação:
- [x] Ter os repositorios na org

**Comment by lucasdutraf** [comment]
O banco a ser utilizado para criação do Boiler-Plate será Postgres.

**Comment by lucasdutraf** [comment]
Disponível em: https://github.com/g1-project/Node-Boiler-Plate
