### ISSUE TITLE
Dojo Docker

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#6]
Criação de um dojo de docker para que o time de MDS aprenderem mais sobre o fluxo de desenvolvimento de software e suas tecnologias.

**Comment by lucasdutraf** [comment]
Dojo realizado para o time de MDS na quinta-feira(04/02).

[Link da apresentação](https://docs.google.com/presentation/d/1WmYAmpqt5M8S8DSqAKMch0ZVUc2KMmimjDOyHzOJM50/edit?usp=sharing).
