### ISSUE TITLE
Estruturar ambiente de banco

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#60]
## Descrição da Issue
Estruturar ambiente de banco

## Tasks:
- [x] Estruturar banco

## Critérios de Aceitação:
- [x] Ter os repositorios na org

**Comment by lucasdutraf** [comment]
O banco a ser utilizado para criação do Boiler-Plate será Postgres.

**Comment by lucasdutraf** [comment]
Essa issue será realizada após a definição da modelagem do banco de dados da aplicação, pois interfere diretamente na decisão de hospedagem.

**Comment by lucasdutraf** [comment]
Issue concluída com a ajuda do @rogerioo e do @youssef-md :100:
