### ISSUE TITLE
Configurar CI back

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#68]
## Descrição da Issue
Configurar CI back

## Tasks:
- [x] Adicionar CI

## Critérios de Aceitação:
- [x] CI funcionando

**Comment by lucasdutraf** [comment]
Nos reuniremos hoje (02/03) para dar início ao trabalho.

**Comment by lucasdutraf** [comment]
CI dos serviços de Flask estáveis.

https://github.com/Lend-it/Rating/pull/2#partial-pull-merging
https://github.com/Lend-it/Request/pull/2
