### ISSUE TITLE
Quadro de conhecimento

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#7]
Criação do quadro de conhecimento para que o time de EPS consiga inferir informações sobre o nível de conhecimento do time de MDS e dessa forma criar pareamentos, acompanhamentos, treinamentos e etc...

**Comment by rogerioo** [comment]
O quadro foi criado e preenchido inicialmente por todos. Esse quadro será atualizado quinzenalmente.

[Quadro de Conhecimento](https://docs.google.com/spreadsheets/d/1aJgCSrpBmd9JbpfTCoV4G_BUO3dXSrnaETJhVWL1RSw/edit?usp=sharing)
