### ISSUE TITLE
Definir arquitetura do projeto

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#72]
## Descrição da Issue
Definir arquitetura do projeto 

## Critérios de Aceitação:
- [x] Documentar na wiki

**Comment by youssef-md** [comment]
O que foi definido:

Front-end(Flutter) + Firebase (notificações)

Serviços:
- Gateway(NodeJS) 
- Usuário(NodeJS) 
- Pedidos(Flask) 
- Avaliação(Flask)
