### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#84]
## Descrição da Issue
Criar o widget Button da aplicação. 

Ele deve receber os seguintes parametros:
1. title - titulo do button
2. tap - função que sera executada ao clica-lo

![image](https://user-images.githubusercontent.com/34384624/110224073-495eda00-7eb7-11eb-834a-a46e1f288199.png)

## Tasks:
- [x] Criar o button
- [x] Chamar em uma tela

## Critérios de Aceitação:
- [x] Estar de acordo com os criterios estabelecidos
- [x] CI passando

**Comment by Thais-ra** [comment]
A gente cria a branch referenciando essa issue lá no repositorio do front?
