### ISSUE TITLE
LendCard

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#86]
## Descrição da Issue
Criar o widget LendCard da aplicação. 

Ele deve receber os seguintes parametros:
1. LendCard - solicitação de ajuda

Deverá criar as seguintes model para isso
1. user - usuario do sistema
2. Lend - solicitação de emprestimo 

![image](https://user-images.githubusercontent.com/34384624/110224302-14538700-7eb9-11eb-9f00-353ff67de6d1.png)

## Tasks:
- [x] Criar o Input
- [x] Chamar em uma tela

## Critérios de Aceitação:
- [x] Estar de acordo com os criterios estabelecidos
- [x] CI passando

**Comment by Matheusafonsouza** [comment]
Componente LendCard criado junto com o @thiagompc 
![image](https://user-images.githubusercontent.com/42722634/110887990-0b542280-82ca-11eb-9bc3-89882324baae.png)

**Comment by Matheusafonsouza** [comment]
Correções do LendCard feitas e alteramos a página em que ele estava.
![image](https://user-images.githubusercontent.com/42722634/111016860-ef668480-838e-11eb-9934-28724671b4a8.png)
