### ISSUE TITLE
Tile

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#87]
## Descrição da Issue
Criar o widget Tile da aplicação. 

Ele deve receber os seguintes parametros:
1. title - titulo do title
2. subtitle - subtitulo do tile

![image](https://user-images.githubusercontent.com/34384624/110224357-a065ae80-7eb9-11eb-9547-d2dc009d3ab9.png)

## Tasks:
- [x] Criar o Tile
- [x] Chamar em uma tela

## Critérios de Aceitação:
- [x] Estar de acordo com os criterios estabelecidos
- [x] CI passando

**Comment by matheusyanmonteiro** [comment]
eu e o @mateuscunhamaia criamos o componente "notification tile" com a ajuda do @youssef-md, @viniciussaturnino  e @Matheusafonsouza.
![image](https://user-images.githubusercontent.com/49919267/110407641-f6c22100-8062-11eb-8dd5-b7d7491d8440.png)
