### ISSUE TITLE
[US22] - Visualizar categorias

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#93]
### Descrição:

Paulo vinícius deseja visualizar uma lista de categorias para poder emprestar com base em uma categoria quer.

### Tarefas:

- [x] Criar Categoria;
- [x] Retornar todas as categorias;

### Critérios de aceitação:

- Paulo vinícius deverá conseguir acessar todas as categorias do Lend.it;
- CI estar passando ;
- Respeitar todas as orientações acima.

### Observações: (caso não tenha, delete essa parte)

- A issue deve ser pontuada;
- A issue deve ser delegada a alguém;
- A issue deve ter labels;

**Comment by EsioFreitas** [comment]
@Thais-ra  e @matheusyanmonteiro 

Esse repositorio ja está configurado e com o seeds. Tirem essa duvida com @lucasdutraf . O trabalho de vcs vai ser preparar um getAll e popular o seeds com os valores reais. Caso vcs terminem mais cedo, vcs dois vão ser distribuidos nos outros dois grupos para ajudar no back deles.

**Comment by lucasdutraf** [comment]
> @Thais-ra e @matheusyanmonteiro
> 
> Esse repositorio ja está configurado e com o seeds. Tirem essa duvida com @lucasdutraf . O trabalho de vcs vai ser preparar um getAll e popular o seeds com os valores reais. Caso vcs terminem mais cedo, vcs dois vão ser distribuidos nos outros dois grupos para ajudar no back deles.

Sim! O @rogerioo configurou isso então assim que vocês subirem os containers, alguns dados mockados serão criados.

**Comment by Thais-ra** [comment]
Já tem algumas categorias pré definidas?

**Comment by rogerioo** [comment]
Eu já mapeei algumas @Thais-ra , mas não tem todas não! Seria bom discutirmos isso na plainning dessa semana

**Comment by lucasdutraf** [comment]
Foi discutido que, como a dupla terminou as tarefas com tempo hábil para execução dos testes, eles também farão parte do critério de aceitação dessa issue. @matheusyanmonteiro @Thais-ra

**Comment by matheusyanmonteiro** [comment]
Okay @lucasdutraf

**Comment by matheusyanmonteiro** [comment]
Eu e a @Thais-ra  fizemos o arquivo de teste com a ajuda do @Matheusafonsouza, já foi feitas as alterações no pull request também.
