### ISSUE TITLE
[US01] -  Criar conta

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#96]
### Descrição:

Paulo vinícius deseja registrar uma conta para começar a utilizar a aplicação.

### Tarefas:

- [x] Criar o serviço de criar uma conta;
- [x] Retornar a conta criada;
- [x] Criar interface para criar uma conta;
- [x] Dar feedback para o usuário se operação finalizou;

### Critérios de aceitação:

- Paulo vinícius deverá conseguir criar uma conta;
- Paulo vinícius deverá se avisado se a criação de conta deu certo;
- Paulo vinícius deverá se avisado se a criação de conta deu errado;
- Paulo vinícius não deverá conseguir criar uma conta ja existente;
- CI estar passando ;
- Respeitar todas as orientações acima.

### Tela
![register-page (1)](https://user-images.githubusercontent.com/34384624/111064102-fa094280-8490-11eb-813b-206e18e6be5f.png)

**Comment by EsioFreitas** [comment]
@viniciussaturnino e @mateuscunhamaia

Recomendo que façam um BaseAuthPage. Vai ser um scaffold que vai ter 3 paremetos (title, subtitle e body)

![recover-password (1)](https://user-images.githubusercontent.com/34384624/111069836-ae18c680-84ad-11eb-889e-49f32a19c03e.png)

Ele deve ficar assim no final.

Isso é legal, pois vcs reaproveitam em outras telas =D

**Comment by mateusmaiamaia** [comment]
![image](https://user-images.githubusercontent.com/48732066/111725292-9347a880-8845-11eb-82e6-b5febb31c6fc.png)
Back-end e front-end finalizados, falta integrá-los.

**Comment by viniciussaturnino** [comment]
![image](https://user-images.githubusercontent.com/49040839/111849546-99dd2b00-88ec-11eb-825e-997d96a11203.png)
Adicionamos o "Voltar para Login embaixo do botão"
