### ISSUE TITLE
[US07] - Cadastrar geolocalização

### ISSUE THREAD

**Issue by EsioFreitas** [fga-eps-mds/2020.2-Lend.it#97]
### Descrição:

Paulo vinícius deseja cadastrar a localização de sua residência para receber ajuda dos vizinhos.

### Tarefas:

- [x] Deve salvar logitude e latitude do usuário;
- [x] Criar interface para ser avisado que está informando a localização dele;

### Critérios de aceitação:

- Paulo vinícius deverá conseguir informar sua localização;
- CI estar passando ;
- Respeitar todas as orientações acima.

### Tela
<img width="411" alt="home-page" src="https://user-images.githubusercontent.com/29265857/111805063-75169280-88af-11eb-8121-7a630f19d3fa.png">

**Comment by EsioFreitas** [comment]
@viniciussaturnino e @mateuscunhamaia 

Nessa issue, recomendo criar um BaseNavigationPage (pensei nesse nome agora, mas caso pense em algo melhor, pode substituir), Vai ser um Scafold e vai receber dois parametros do tipo Widget (header e body)

![home-page (1)](https://user-images.githubusercontent.com/34384624/111069670-ecfa4c80-84ac-11eb-8e3a-d480f13f9de7.png)

Ele deve ficar assim no final. 

Isso é legal, pois vcs reaproveitam em outras telas =D

**Comment by youssef-md** [comment]
A tela de pedidos é uma TabBar, ela funcionaria nessa BaseNavigationPage ? ou seria melhor só fazer esse Header como um componente e definir o padding padrão como uma variável que todas as telas importariam?

<img width="411" alt="home-page" src="https://user-images.githubusercontent.com/29265857/111491908-0274ae00-871b-11eb-844a-c0f8d4291575.png">

**Comment by EsioFreitas** [comment]
@youssef-md , funcionaria, pois está recebendo dois widget. O header seria a  TabBar e o body um array de widget na posição clicada.

**Comment by viniciussaturnino** [comment]
![image](https://user-images.githubusercontent.com/49040839/111840151-b83a2b00-88da-11eb-8860-a4e6c5238c11.png)
Criamos a base page e falta finalizar a geolocation page passando o header e o body

**Comment by viniciussaturnino** [comment]
![image](https://user-images.githubusercontent.com/49040839/111842566-6b585380-88de-11eb-9bd6-8348351a5751.png)
Finalizamos a geolocation page
